parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''
    env(APP_NAME): 'MaDocIT'
    env(APP_VERSION): '0.1'

api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            # On ajoute le chemin vers le fichier de configurations des annotations d'entit√©
            - '%kernel.project_dir%/config/api_platform'
    title: '%env(APP_NAME)%'
    version: '%env(APP_VERSION)%'
    # Enable the Varnish integration
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
